version: '3.3'

services:
  myapp:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "0.0.0.0:3001:3001"
    expose:
        - "3001"    
    environment:
        HOST: 0.0.0.0
        PORT: 3001
        NODE_ENV: development
        API_PORT: 3000
        API_BASE_URL: http://myapi:3000
    command: ["npm", "start"]

networks:
    default:
        external:
            name: api_default